### ISSUE TITLE
prior parameter constraints & a little question about spec_importer & parallel

### ISSUE THREAD

**Issue by hermione-evans** [andrea-mitridate/PTArcade#42]
**Describe the bug**
a) Is there a way to impose constraints on parameters using specific settings? For instance, assuming I have parameters 
a and b with a Uniform prior ranging from [0,1], I'd like to enforce a condition where x≥y. This is reminiscent of the example found in [Bilby's documentation](https://lscsoft.docs.ligo.org/bilby/prior.html#prior-constraints).

b) The documentation provides a method for importing a spectrum:

```
log_spectrum = spec_importer(path)
def spectrum(f, p):
    return 10**log_spectrum(np.log10(f), p=p)
```

Given this, is it feasible to modify the log_spectrum function to accommodate additional parameters and subsequently retrieve the final spectrum as demonstrated below?
```
def spectrum(f, p, A):
    return A * 10**log_spectrum(np.log10(f), p=p)
```
c) Is this package capable of parallel execution on both High-Performance Computing (HPC) systems and personal PCs? If so, how can one configure the number of threads or cores utilized by the package?

**Comment by davecwright3** [comment]
> a) Is there a way to impose constraints on parameters using specific settings? For instance, assuming I have parameters
a and b with a Uniform prior ranging from [0,1], I'd like to enforce a condition where x≥y. This is reminiscent of the example found in [Bilby's documentation](https://lscsoft.docs.ligo.org/bilby/prior.html#prior-constraints).

This is being worked on upstream in [enterprise](https://github.com/nanograv/enterprise). We will add this functionality + documentation to `PTArcade` once it releases in `enterprise`

> Given this, is it feasible to modify the log_spectrum function to accommodate additional parameters and subsequently retrieve the final spectrum as demonstrated below?

I'm a little confused because `log_spectrum` hasn't been modified at all in your example. But assuming you mean to ask if it's possible to include additional parameters in an imported spectrum---yes that is possible. See `sigw_box` [here](https://zenodo.org/record/8092761) as an example. You just need to have that extra column for the additional parameter in your tabulated data, then you should pass that parameter to `log_spectrum` just like `p` in our example.

> c) Is this package capable of parallel execution on both High-Performance Computing (HPC) systems and personal PCs? If so, how can one configure the number of threads or cores utilized by the package?

If you'd like to run multiple chains in parallel, the current best option is launching multiple jobs with the scheduler on your cluster. SLURM job arrays work well for this. On a personal machine without a scheduler, you'd need to launch multiple jobs by hand.

The package itself is not multi-threaded or parallelized. You may, however, see usage of more than one thread by `numpy`, `scipy`, etc. if your `BLAS` library supports multi-threading

**Comment by andrea-mitridate** [comment]
Regarding your first question, as a temporary solution, you could try modifying your `spectrum` function such that when $x < y$ it returns a ridiculously large value (assuming that you are considering a stochastic signal). 

By doing this, the sampler should ignore all the points that do not satisfy the condition $x\geq y$ as they have a very small posterior.

**Comment by hermione-evans** [comment]
Thanks a lot for your reply!
